services:

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
   
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
